#!/bin/sh
# decompile the functions containing the given hex addresses; output on stdout
here=$(cd "$(dirname "$0")" && pwd)
# The Ghidra of the locked nixpkgs, fetched by revision: going through the
# flake itself would copy the whole tree into the store on every edit.
rev=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["nodes"]["nixpkgs"]["locked"]["rev"])' "$here/../flake.lock")
nix shell "github:NixOS/nixpkgs/$rev#ghidra" --command ghidra-analyzeHeadless "$here/project" sp404 -process sdram_code.bin -noanalysis -readOnly -scriptPath "$here/scripts" -postScript DecompAt.java "$@" 2>&1 | awk '/@@@/{p=1} /INFO  (REPORT|ANALYZING|Headless)/{p=0} p' | sed 's/^INFO  DecompAt.java> //; s/ (GhidraScript)  $//'
